FROM centos:latest
RUN yum update -y
RUN yum install httpd net-tools -y
RUN /bin/mkdir -p /var/www/html
RUN /bin/echo "This is a test file for Devops Class 20" >> /var/www/html/index.html
EXPOSE 80
ENTRYPOINT apachectl "-DFOREGROUND"
